source 'https://rubygems.org'
  ruby '2.7.0'

  gem 'httparty'
  gem 'twilio-ruby'
  gem 'pry'
  gem 'json'
  gem 'actionview'
  gem 'dotenv'
  gem 'chronic'
  gem 'activerecord'
  gem 'pg'
  gem 'nokogiri'
